version: '3.8'
services:
  # Backend (Express)
  backend:
    build: ./backend  # Asegúrate de que tu backend tenga su propio Dockerfile
    ports:
      - "3000:3000"  # Backend en puerto 3000 (para API)
    environment:
      - NODE_ENV=production
    # Opcional: Volumen para desarrollo (hot-reload)
    # volumes:
    #   - ./backend:/usr/src/app

  # Frontend (JS estático con http-server)
  frontend:
    build: ./frontend  # Ruta a tu carpeta frontend (con el Dockerfile de http-server)
    ports:
      - "8080:8080"  # Frontend en puerto 8080 (http://localhost:8080)
    depends_on:
      - backend  # Espera a que el backend esté listo
    # Opcional: Volumen para desarrollo (hot-reload)
    # volumes:
      - ./frontend:/app